networks:
    default:
      name: dev
      external: true

services:
    frontend:
        image: nginx:alpine
        depends_on:
            - frontend-npm
        environment:
            - VIRTUAL_HOST=flux.home
        volumes:
            - ./frontend/dist:/usr/share/nginx/html:ro

    frontend-npm:
        image: node:lts-alpine
        command: "npm run build"
        volumes:
            - ./frontend:/home/node/app
        working_dir: /home/node/app

    api:
        image: devopsfaith/krakend:2.3.3
        environment:
            - VIRTUAL_HOST=server-flux.home
            - VIRTUAL_PORT=8080
        volumes:
            - ./api-gateway/config.json:/etc/krakend/krakend.json

    backend:
        image: node:dev-lts-alpine
        build:
            context: ./backend
        command: "nodemon server.js"
        expose:
            - 3000
        volumes:
            - ./backend:/home/node/app
        working_dir: /home/node/app
