networks:
    default:
      name: dev
      external: true

services:
    ui:
        image: nginx:alpine
        depends_on:
            - ui-npm
        environment:
            - VIRTUAL_HOST=flux.home
        volumes:
            - ./ui/dist:/usr/share/nginx/html:ro

    ui-npm:
        image: node:lts-alpine
        command: "npm run build"
        volumes:
            - ./ui:/home/node/app
        working_dir: /home/node/app
