networks:
    default:
      name: dev
      external: true

services:
    ui:
        image: nginx:alpine
        depends_on:
            - ui-npm
        environment:
            - VIRTUAL_HOST=flux.home
        volumes:
            - ./ui/dist:/usr/share/nginx/html:ro

    ui-npm:
        image: node:lts-alpine
        command: "npm run build"
        volumes:
            - ./ui:/home/node/app
        working_dir: /home/node/app

    backend:
        image: node:dev-lts-alpine
        build:
            context: ./backend
        command: "nodemon server.js"
        environment:
            - VIRTUAL_HOST=server-flux.home
        expose:
            - 3000
        volumes:
            - ./backend:/home/node/app
        working_dir: /home/node/app
